<?php


use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//    Проверка данных на валидность  



// echo '<pre>';
// print_r($_SERVER);

$uri = parse_url($_SERVER['REQUEST_URI']);
// print_r($uri);

if($uri['path'] == '/6-oy/7-dars/index.html'){
    include ('../6-oy/7-dars/index.php');
}

else if($uri['path'] == '/1-oy/1'){
    echo file_get_contents('../1-oy/1-dars/index.html');
}
else if($uri['path'] == '/1-oy/2'){
    echo file_get_contents('../1-oy/2-dars/index.html');
}
else if($uri['path'] == '/6-oy/8')   require('../6-oy/8-dars/index.php');
else if($uri['path'] == '/6-oy/8/api') {

    require('../6-oy/8-dars/api.php');  

}

else if($uri['path'] == '/6-oy/10')   require('../6-oy/10-dars/index.php');

else if($uri['path'] == '/6-oy/11')   require('../6-oy/11-dars/index.php');


else if($uri['path'] == '/mail'){


    $IP = '127.1.1.1@mail.ru';

    echo filter_var($IP,FILTER_VALIDATE_EMAIL);
    die;

   
    require 'PHPMailer/src/Exception.php';
    require 'PHPMailer/src/PHPMailer.php';
    require 'PHPMailer/src/SMTP.php';


    
    $mail = new PHPMailer();

    $mail->isSMTP();
    $mail->Host = 'smtp.mailtrap.io';
    $mail->SMTPAuth = true;
    $mail->Username = '851831e978ecd4'; //paste one generated by Mailtrap
    $mail->Password = '9a58b344364e11'; //paste one generated by Mailtrap
    $mail->SMTPSecure = 'tls';
    $mail->Port = 2525;



    try {


    //     $mail->setFrom('info@mailtrap.io', 'Mailtrap');
    //     $mail->addReplyTo('info@mailtrap.io', 'Mailtrap');
    //     $mail->addAddress('recipient1@mailtrap.io', 'Tim'); 
    //     $mail->addCC('cc1@example.com', 'Elena');
    //     $mail->addBCC('bcc1@example.com', 'Alex');
    //     $mail->Subject = 'Test Email via Mailtrap SMTP using PHPMailer';
    //     $mail->isHTML(true);
    //     $mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
    //     <p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
    //     $mail->Body = $mailContent;

    //     if($mail->send()){
    //         echo 'Message has been sent';
    //     }else{
    //         echo 'Message could not be sent.';
    //         echo 'Mailer Error: ' . $mail->ErrorInfo;
    //     }



        
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }





    //CODE1234LIFE1234UZ


    
    $to  = 'telegram.org@mail.ru';
    $subject = 'the subject';
    $message = '<b>hello</b>';
    $headers = 'From: webmaster@example.com' . "\r\n" .
    'Reply-To: webmaster@example.com' . "\r\n" .
    'Content-type: text/html; charset=utf-8'.
    'X-Mailer: PHP/' . phpversion();

    if(mail($to, $subject, $message, $headers)){
        echo 'Habar yuborildi';
    }else{
        echo 'Error';
    }
}

else {
echo 'Not found';
}
// echo '</pre>';
